Add general improvements for the deployment file and the frontend

diff --git a/scripts/hercules b/scripts/hercules
--- a/scripts/hercules
+++ b/scripts/hercules
@@ -1,4 +1,6 @@
 #!/bin/bash
+## Last modification: 18/12/2023
+# set -x
 #######################################################
 #######################################################
 ## To stop all servers.
@@ -51,7 +53,7 @@ WaitForServers() {
 STATUS=$1
 shift
 if [[ $STATUS != "stop" && $STATUS != "start" ]]; then
-    echo "Incorrect argument in STATUS option, usage: hercules <start|stop> [OPTION]"
+    echo "Incorrect argument in STATUS option, usage: hercules <start|stop>"
     exit 1
 fi
 
@@ -70,31 +72,6 @@ do
     esac
 done
 
-HOSTFILES_OPTION=-1
-if [ ! -z "$DATA_SERVER_FILE" ]; then
-    echo "Data server file - $DATA_SERVER_FILE"
-    if [ ! -f "$DATA_SERVER_FILE" ]; then
-        echo "Data server file " $DATA_SERVER_FILE " does not exists"
-        exit 0
-    fi
-    HOSTFILES_OPTION=1
-fi
-if [ ! -z "$META_SERVER_FILE" ]; then
-    echo "Meta server file - $META_SERVER_FILE"
-    if [ ! -f "$META_SERVER_FILE" ]; then
-        echo "Meta server file " $META_SERVER_FILE " does not exists"
-        exit 0
-    fi
-    HOSTFILES_OPTION=1
-fi
-if [ ! -z "$HERCULES_MPI_HOSTFILE_NAME" ]; then
-    echo "Client file - $HERCULES_MPI_HOSTFILE_NAME"
-    if [ ! -f "$HERCULES_MPI_HOSTFILE_NAME" ]; then
-        echo "Client deployment file " $HERCULES_MPI_HOSTFILE_NAME " does not exists"
-        exit 0
-    fi
-    HOSTFILES_OPTION=1
-fi
 
 SLURM=-1
 # If slurm option is set by the user (optional).
@@ -112,13 +89,53 @@ if [[ ! -z "$SLURM_OPTION" ]]; then
     esac
 fi
 
-if [[ $SLURM -eq "-1" && $HOSTFILES_OPTION -eq "-1" ]]; then
+# if [[ "$SLURM" -eq "-1" && $HOSTFILES_OPTION -eq "-1" ]]; then
+# if slurm option is not set by the user, we check if it is installed.
+if [[ "$SLURM" -eq "-1" ]]; then
     ## If not slurm option set by user and hostnames were not specify.
     ## Verify if slurm is installed by using the env variable.
     SLURM=$([ -z "$SLURM_CLUSTER_NAME" ] && echo 0 || echo 1)
-elif [[ $SLURM -eq "1" && $HOSTFILES_OPTION -eq "1" ]]; then
+#elif [[ "$SLURM" -eq "1" && $HOSTFILES_OPTION -eq "1" ]]; then
     ## If slurm option set by user and hostnames were specify. 
-    echo "Inconsistency found, SLURM option (-s 1) and hostfiles (-m, -d, -c) could not be used together. Set "-s 0" or remove hostfile options."
+#    echo "Inconsistency found, SLURM option (-s 1) and hostfiles (-m, -d, -c) could not be used together. Set "-s 0" or remove hostfile options."
+fi
+
+# If slurm is not use, we hope user set three hostfiles (for metadata, data and clients).
+SERVERS_HOSTFILES_OPTION=0
+if [[ "$SLURM" -eq "0" ]]; then
+    if [ ! -z "$DATA_SERVER_FILE" ]; then
+        echo "Data server file - $DATA_SERVER_FILE"
+        if [ ! -f "$DATA_SERVER_FILE" ]; then
+            echo "Data server file " $DATA_SERVER_FILE " does not exists"
+            exit 0
+        fi
+        # HOSTFILES_OPTION=1
+        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
+    fi
+    if [ ! -z "$META_SERVER_FILE" ]; then
+        echo "Meta server file - $META_SERVER_FILE"
+        if [ ! -f "$META_SERVER_FILE" ]; then
+            echo "Meta server file " $META_SERVER_FILE " does not exists"
+            exit 0
+        fi
+        # SERVERS_HOSTFILES_OPTION=1
+        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
+    fi
+    # client hostfile is optional.
+    if [ ! -z "$HERCULES_MPI_HOSTFILE_NAME" ]; then
+        echo "Client file - $HERCULES_MPI_HOSTFILE_NAME"
+        if [ ! -f "$HERCULES_MPI_HOSTFILE_NAME" ]; then
+            echo "Client deployment file " $HERCULES_MPI_HOSTFILE_NAME " does not exists"
+            exit 0
+        fi
+        # SERVERS_HOSTFILES_OPTION=1
+        #SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
+    fi
+    # if a server hostfile is missing. 
+    if [  ! "$SERVERS_HOSTFILES_OPTION" -eq "2" ]; then
+        echo "One or more hostfiles missing for the servers, please specify them with: -m <metadata_hostfile> -d <data_hostfile>"
+        exit 0
+    fi
 fi
 
 if [ ! "$SLURM" -eq "-1" ]; then
@@ -145,24 +162,8 @@ if [ ! -z "$FILE" ]; then ## Checks if a configuration file was provided by the 
     fi
 fi
 
-## Checks if the user wants to stop the services.
-if [[ $STATUS = "stop" ]];
-then
-    # if [[ "$SLURM" -eq "0" ]]; then
-    ## Stops data and metadata servers.
-    readarray -t hosts < data_hostfile
-    echo "hosts=$hosts"
-    StopServers "data" $hosts
-    
-    readarray -t hosts < meta_hostfile
-    echo "hosts=$hosts"
-    StopServers "metadata" $hosts
-    # fi
-    exit 0
-fi
 
 ## Define values.
-
 ## If a configuration file was not provided.
 if [ -z "$FILE" ]; then
     ## To know if a configuration file exists in the default paths.
@@ -185,24 +186,34 @@ echo "Reading configuration from $FILE"
 export HERCULES_CONF="$FILE"
 
 
-## If slurm is used, then we create a hostfile containing the allocated nodes.
-if [[ $SLURM -eq "1" ]]; then
-    srun -pernode hostname |sort > hostfile
+## If hostfiles was not set, then we create a hostfile containing the allocated nodes.
+# if [[ $SLURM -eq "1" ]]; then
+if [[ $SERVERS_HOSTFILES_OPTION -eq "0" ]]; then
+    #srun -pernode hostname |sort > hostfile
+    scontrol show hostnames "$SLURM_JOB_NODELIST" > hostfile
 fi
 
-if [ -z "$FILE" ]; then
-    HERCULES_PATH=$(dirname `pwd`)
+
+IS_SPACK=$([ -z $(whereis hercules | awk '{print $2}') ] && echo 0 || echo 1)
+if [[ "$IS_SPACK" -eq "1" ]]; then
+    HERCULES_PATH=$(spack find --paths --loaded hercules | grep hercules | awk '{print $2}')
+    HERCULES_BUILD_PATH=$HERCULES_PATH/bin
+    HERCULES_BASH_PATH=$HERCULES_PATH/bin
+    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/lib/libhercules_posix.so"
 else
-    HERCULES_PATH=$(cat $FILE | grep "HERCULES_PATH" | awk '{print $3}')
+    if [ -z "$FILE" ]; then
+        HERCULES_PATH=$(dirname `pwd`)
+    else
+        HERCULES_PATH=$(cat $FILE | grep "HERCULES_PATH" | awk '{print $3}')
+    fi
+    export HERCULES_PATH=$HERCULES_PATH
+    HERCULES_BUILD_PATH=$HERCULES_PATH/build
+    HERCULES_BASH_PATH=$HERCULES_PATH/scripts
+    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/build/tools/libhercules_posix.so"
 fi
 
 echo "Hercules path - $HERCULES_PATH"
 
-export HERCULES_PATH=$HERCULES_PATH
-
-HERCULES_BUILD_PATH=$HERCULES_PATH/build
-HERCULES_BASH_PATH=$HERCULES_PATH/bash
-HERCULES_POSIX_PRELOAD="$HERCULES_PATH/build/tools/libhercules_posix.so"
 
 
 ## Read configuration file.
@@ -222,6 +233,24 @@ HERCULES_METADATA_HOSTFILE=$(cat $FILE | grep "METADATA_HOSTFILE" | awk '{print 
 
 ## \< \> to match exact word.
 
+## Checks if the user wants to stop the services.
+if [[ $STATUS = "stop" ]];
+then
+    ## Stops data and metadata servers.
+    # readarray -t hosts < data_hostfile
+    readarray -t hosts < $HERCULES_DATA_HOSTFILE
+    echo "data hosts=$hosts"
+    StopServers "data" $hosts
+    
+    # readarray -t hosts < meta_hostfile
+    readarray -t hosts < $HERCULES_METADATA_HOSTFILE
+    echo "meta hosts=$hosts"
+    StopServers "metadata" $hosts
+    # fi
+    exit 0
+fi
+
+
 
 
 echo HERCULES_MOUNT_POINT - "$HERCULES_MOUNT_POINT" - HERCULES_BLOCK_SIZE - "$HERCULES_BLOCK_SIZE"
@@ -230,6 +259,7 @@ echo HERCULES_MOUNT_POINT - "$HERCULES_MOUNT_POINT" - HERCULES_BLOCK_SIZE - "$HE
 if [ -z "$HERCULES_MPI_HOSTFILE_NAME" ]; then
     ## Warning if slurm is not being used and no client hostfile was defined.
     if [[ $SLURM -eq "0" ]]; then
+    # if [[ $HOSTFILES_OPTION -eq "-1" ]]; then
         echo "[Warning] Client hostfile not specified, you can specify it with -c <filename> flag."
         # exit 1
     fi
@@ -362,10 +392,6 @@ runtime=$( echo "$end - $start" | bc -l )
 echo "[-] Data servers started in $runtime seconds"
 
 
-
-export HERCULES_NCPN=$NUM_CLIENTS_PER_NODE
-export HERCULES_NNFC=$NUM_NODES_FOR_CLIENTS
-
 ## Search for the mpi distribution installed.
 for MPI_DS in {"open-mpi","mpich","Intel"}
 do
@@ -398,6 +424,10 @@ case $MPI_DS in
     ;;
 esac
 
+# set enviroment variables.
+export HERCULES_NCPN=$NUM_CLIENTS_PER_NODE
+export HERCULES_NNFC=$NUM_NODES_FOR_CLIENTS
+
 
 unset META_PORT
 unset DATA_PORT
@@ -419,35 +449,35 @@ unset STORAGE_SIZE
     echo -e "#############################################################################
     [!] 1. To export the path of the configuration file, run the following command:
     ${GREEN}
-    export HERCULES_CONF=$FILE
+export HERCULES_CONF=$FILE
     ${NC}
     #############################################################################"
 
     echo -e "#############################################################################
     [!] 2. To load the client library:
     ${GREEN}
-    "export LD_PRELOAD=$HERCULES_POSIX_PRELOAD"
+export LD_PRELOAD=$HERCULES_POSIX_PRELOAD
     ${NC}
     #############################################################################"
 
     echo -e "#############################################################################
     [!] 2. To unload the client library:
     ${RED}
-    "unset LD_PRELOAD=$HERCULES_POSIX_PRELOAD"
+unset LD_PRELOAD=$HERCULES_POSIX_PRELOAD
     ${NC}
     #############################################################################"
 
     echo -e "#############################################################################
     [!] To stop the services:
     ${RED}
-    hercules stop
+hercules stop
     ${NC}
     #############################################################################"
 
     echo -e "#############################################################################
     [!] Warning: due to UCX bug (Shared memory error) it is sometimes necesary to run:
     ${YELLOW}
-    export UCX_POSIX_USE_PROC_LINK=n
+export UCX_POSIX_USE_PROC_LINK=n
     ${NC}
     #############################################################################"
 
